<?php

namespace ContainerLhO2tQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Product' shared autowired service.
     *
     * @return \App\Entity\Product
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Product.php';

        return $container->privates['App\\Entity\\Product'] = new \App\Entity\Product();
    }
}
