<?php

namespace ContainerLhO2tQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveAllProductsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\RemoveAllProductsCommand' shared autowired service.
     *
     * @return \App\Command\RemoveAllProductsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/RemoveAllProductsCommand.php';

        $container->privates['App\\Command\\RemoveAllProductsCommand'] = $instance = new \App\Command\RemoveAllProductsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:remove-all-products');
        $instance->setDescription('Removes all products from the database');

        return $instance;
    }
}
