<?php

namespace ContainerLhO2tQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveAllProductsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\RemoveAllProductsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\RemoveAllProductsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:remove-all-products', [], 'Removes all products from the database', false, #[\Closure(name: 'App\\Command\\RemoveAllProductsCommand')] fn (): \App\Command\RemoveAllProductsCommand => ($container->privates['App\\Command\\RemoveAllProductsCommand'] ?? $container->load('getRemoveAllProductsCommandService')));
    }
}
