<?php

namespace ContainerLhO2tQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateProductImagesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\UpdateProductImagesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\UpdateProductImagesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:update-product-images', [], 'Updates existing product images', false, #[\Closure(name: 'App\\Command\\UpdateProductImagesCommand')] fn (): \App\Command\UpdateProductImagesCommand => ($container->privates['App\\Command\\UpdateProductImagesCommand'] ?? $container->load('getUpdateProductImagesCommandService')));
    }
}
