<?php

namespace Container4ROnoCV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CartController' shared autowired service.
     *
     * @return \App\Controller\CartController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CartController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CartService.php';

        $a = ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService'));

        $container->services['App\\Controller\\CartController'] = $instance = new \App\Controller\CartController($a, new \App\Service\CartService(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\CartController', $container));

        return $instance;
    }
}
