<?php

namespace ContainerXKxE9xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSampleProductsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateSampleProductsCommand' shared autowired service.
     *
     * @return \App\Command\CreateSampleProductsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateSampleProductsCommand.php';

        $container->privates['App\\Command\\CreateSampleProductsCommand'] = $instance = new \App\Command\CreateSampleProductsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:create-sample-products');
        $instance->setDescription('Creates sample miniature car products');

        return $instance;
    }
}
