<?php

namespace ContainerXKxE9xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vCPEyuw.App\Controller\HomeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vCPEyuw.App\\Controller\\HomeController::index()'] = ($container->privates['.service_locator.vCPEyuw'] ?? $container->load('get_ServiceLocator_VCPEyuwService'))->withContext('App\\Controller\\HomeController::index()', $container);
    }
}
