<?php

namespace ContainerT0yB5tb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZEQr2LSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zEQr2LS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zEQr2LS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CartController::add' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\CartController::remove' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\CartController::remove()', 'getCartControllerremoveService', true],
            'App\\Controller\\CartController::update' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\CartController::update()', 'getCartControllerupdateService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CartController:add' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\CartController:remove' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\CartController::remove()', 'getCartControllerremoveService', true],
            'App\\Controller\\CartController:update' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\CartController::update()', 'getCartControllerupdateService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CartController::add' => '?',
            'App\\Controller\\CartController::remove' => '?',
            'App\\Controller\\CartController::update' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CartController:add' => '?',
            'App\\Controller\\CartController:remove' => '?',
            'App\\Controller\\CartController:update' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
