<?php

namespace ContainerT0yB5tb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSampleProductsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateSampleProductsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateSampleProductsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-sample-products', [], 'Creates sample miniature car products', false, #[\Closure(name: 'App\\Command\\CreateSampleProductsCommand')] fn (): \App\Command\CreateSampleProductsCommand => ($container->privates['App\\Command\\CreateSampleProductsCommand'] ?? $container->load('getCreateSampleProductsCommandService')));
    }
}
