<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKxE9xR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKxE9xR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXKxE9xR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXKxE9xR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXKxE9xR\App_KernelDevDebugContainer([
    'container.build_hash' => 'XKxE9xR',
    'container.build_id' => '003eeeab',
    'container.build_time' => 1748774870,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKxE9xR');
